// Code generated by `generate`. DO NOT EDIT.

package kittycad

// UnauthorizedResponse is the response given when no valid API key provided.
type UnauthorizedResponse ErrorMessage

// BadRequestResponse is the response given when the request failed could not authenticate, but the token existed.
type BadRequestResponse ErrorMessage

// ForbiddenResponse is the response given when the API key doesn't have permissions to perform the request.
type ForbiddenResponse ErrorMessage

// InternalServerErrorResponse is the response given when the server encountered an unexpected condition that prevented it from fulfilling the request.
type InternalServerErrorResponse ErrorMessage

// NotAcceptableResponse is the response given when the request was unacceptable, often due to missing a required parameter.
type NotAcceptableResponse ErrorMessage

// NotFoundResponse is the response given when the requested resource doesn't exist.
type NotFoundResponse ErrorMessage
