on:
  push:
    branches:
      - main
    paths:
      - '**.rs'
      - 'rust-toolchain.toml'
      - .github/workflows/cargo-fmt.yml
  pull_request:
    paths:
      - '**.rs'
      - 'rust-toolchain.toml'
      - .github/workflows/cargo-fmt.yml
permissions:
  packages: read
  contents: read
name: cargo fmt
jobs:
  cargofmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install latest rust
        uses: dtolnay/rust-toolchain@stable
        with:
            components: rustfmt

      - name: Run cargo fmt
        run: |
          cargo fmt -- --check
        shell: bash
