name: cargo test

on:
  push:
    branches:
      - main
    paths:
      - '**.rs'
      - '**.rs.gen'
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-test.yml
      - 'rust-toolchain.toml'
      - 'Makefile'
      - 'spec.json'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * * # hourly

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cargotest:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install latest rust
        uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: stable
            override: true
      - name: Cache cargo registry
        uses: actions/cache@v6.1.0
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v6.1.0
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache@v6.1.0
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: taiki-e/install-action@nextest
      - uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run tests with coverage
        run: |-
          cargo llvm-cov nextest \
            --workspace --lcov --output-path lcov.info --no-fail-fast \
            --profile=ci || true  # let TAB determine failure
          .github/workflows/lib/upload-results.sh
        env:
          ZOO_TEST_TOKEN: ${{secrets.KITTYCAD_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUST_BACKTRACE: 1
          TAB_API_URL: ${{ vars.TAB_API_URL }}
          TAB_API_KEY: ${{ secrets.TAB_API_KEY }}
          CI_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          CI_PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v7
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
          flags: unittests
          files: lcov.info
          verbose: true
