on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.go'
      - 'Makefile'
      - 'Dockerfile'
      - '.github/workflows/make-image.yml'
      - 'go.mod'
      - 'go.sum'
name: make-image
jobs:
  makeimage:
    name: make-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make image
        run: make image
        shell: bash
