on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.go'
      - 'Makefile'
      - '.github/workflows/make-all.yml'
      - 'go.mod'
      - 'go.sum'
name: make-all
jobs:
  makeall:
    name: make-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'
      - name: make all
        shell: bash
        run: |
          make all
      - name: make cross compile
        shell: bash
        run: |
          make release
      - name: make test coverage
        shell: bash
        run: |
          make cover
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: unittests
          files: ${{ github.workspace }}/coverage.txt
          verbose: true
