name: win-ca-smoke

permissions:
  contents: read
  # Add more granular permissions if later required

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  smoke:
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22]
    uses: kittycad/gh-action-win-ca/.github/workflows/win-ca-smoke.yml@main
    with:
      node-version: ${{ matrix.node }}
      setup-rust: true
      pre-test-command: cargo test --test win_ca_smoke -- --nocapture
      post-test-command: cargo test --test win_ca_smoke -- --nocapture
    env:
      RUST_BACKTRACE: '1'
      SMOKE_URL: 'https://127.0.0.1:4443/' # only needed for the CLI binary
